version: "2"

services:
  mealmonitor-keycloak:
    image: bitnami/keycloak:23.0.3
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=mealmonitor
      - KEYCLOAK_ADMIN_PASSWORD=numiplacesamananc
      - KEYCLOAK_MANAGEMENT_USER=mealmonitor
      - KEYCLOAK_MANAGEMENT_PASSWORD=numiplacesamananc
      - KEYCLOAK_HOSTNAME=localhost
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_ENABLE_HTTPS=false
      - KEYCLOAK_BIND_ADDRESS=0.0.0.0
      - KEYCLOAK_DATABASE_HOST=mealmonitor-database-local
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=mealmonitor
      - KEYCLOAK_DATABASE_USER=mealmonitor
      - KEYCLOAK_DATABASE_PASSWORD=numiplacesamananc
      - KEYCLOAK_DATABASE_SCHEMA=public
    ports:
      - "80:8080"

  mealmonitor-database-local:
    image: postgres:15.3
    container_name: mealmonitor-database-local
    restart: unless-stopped
    ports:
      - 63587:5432
    environment:
      - POSTGRES_DB=mealmonitor
      - POSTGRES_USER=mealmonitor
      - POSTGRES_PASSWORD=numiplacesamananc
      - TZ=UTC
      - PGTZ=UTC
    volumes:
      - mealmonitor-database:/var/lib/postgresql/data

volumes:
  mealmonitor-database:
