version: "2"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: 'keycloak.mealmonitor.galitianu.com'
      KC_PROXY: 'edge'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'numiplacesamananc'
      KEYCLOAK_DATABASE_HOST: 'mealmonitor-database'
      KEYCLOAK_DATABASE_PORT: '5432'
      KEYCLOAK_DATABASE_NAME: 'mealmonitor'
      KEYCLOAK_DATABASE_USER: 'mealmonitor'
      KEYCLOAK_DATABASE_PASSWORD: 'numiplacesamananc'
      KEYCLOAK_DATABASE_SCHEMA: 'public'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealmonitor-keycloak.rule=Host(`keycloak.mealmonitor.galitianu.com`)"
      - "traefik.http.services.mealmonitor-keycloak.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.custom-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.custom-redirect.redirectregex.replacement=https://$$1/admin"
      - "traefik.http.routers.mealmonitor-keycloak.middlewares=custom-redirect"
      - "traefik.http.routers.mealmonitor-keycloak.entrypoints=websecure"
      - "traefik.http.routers.mealmonitor-keycloak.tls.certresolver=myresolver"
    networks:
      - traefik_default
    restart: unless-stopped

  mealmonitor-database:
    image: postgres:15.3
    container_name: mealmonitor-database
    restart: unless-stopped
    hostname: mealmonitordb
    environment:
      - POSTGRES_DB=mealmonitor
      - POSTGRES_USER=mealmonitor
      - POSTGRES_PASSWORD=numiplacesamananc
    volumes:
      - mealmonitor-database:/var/lib/postgresql/data
    networks:
      - traefik_default


  mealmonitor-backend:
    image: mealmonitor-backend
    container_name: mealmonitor-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILE=docker
      - DB_HOST=mealmonitordb
      - DB_PORT=5432
      - DB_SCHEMA=mealmonitor
      - DB_USERNAME=mealmonitor
      - DB_PASSWORD=numiplacesamananc
    labels:
      - "traefik.http.services.mealmonitor-api.loadbalancer.server.port=8088"
      - "traefik.enable=true"
      - "traefik.http.routers.mealmonitor-api.rule=Host(`api.mealmonitor.galitianu.com`)"
      - "traefik.http.routers.mealmonitor-api.entrypoints=websecure"
      - "traefik.http.routers.mealmonitor-api.tls.certresolver=myresolver"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
  internal:
    ipam:
      config:
        - subnet: 172.16.49.0/24

volumes:
  mealmonitor-database:
